Etch.OrchardCore.Leaflet/Models/Map.cs
using Newtonsoft.Json;
using OrchardCore.ContentFields.Fields;
using OrchardCore.ContentManagement;

namespace Etch.OrchardCore.Leaflet.Models
{
    public class Map : ContentPart
    {
        [JsonIgnore]
        public decimal InitialZoom
        {
            get { return this.Get<NumericField>(Constants.MapInitialZoomFieldName)?.Value ?? Constants.DefaultInitialZoom; }
        }

        [JsonIgnore]
        public decimal MaxZoom
        {
            get { return this.Get<NumericField>(Constants.MapMaxZoomFieldName)?.Value ?? Constants.DefaultMaxZoom; }
        }

        [JsonIgnore]
        public decimal MinZoom
        {
            get { return this.Get<NumericField>(Constants.MapMinZoomFieldName)?.Value ?? Constants.DefaultMinZoom; }
        }

        [JsonIgnore]
        public bool MouseWheelZoom
        {
            get { return this.Get<BooleanField>(Constants.MapMouseWheelZoom)?.Value ?? Constants.DefaultMouseWheelZoom; }
        }

        [JsonIgnore]
        public string ZoomControlPosition
        {
            get { return this.Get<TextField>(Constants.MapZoomControlPositionFieldName)?.Text ?? Constants.DefaultZoomControlPosition; }
        }
    }
}

Etch.OrchardCore.Leaflet/ViewModels/MapViewModel.cs
using Etch.OrchardCore.Leaflet.Dtos;
using OrchardCore.ContentManagement;
using System.Collections.Generic;

namespace Etch.OrchardCore.Leaflet.ViewModels
{
    public class MapViewModel
    {
        public MapAnalyticsViewModel Analytics { get; set; }
        public ContentItem ContentItem { get; set; }
        public int Height { get; set; }
        public decimal InitialZoom { get; set; }
        public IEnumerable<PoiMarker> Markers { get; set; }
        public decimal MaxZoom { get; set; }
        public decimal MinZoom { get; set; }
        public bool MouseWheelZoom { get; set; }
        public string TileRoot { get; set; }
        public int Width { get; set; }
        public string ZoomControlPosition { get; set; }

        public double Ratio
        {
            get
            {
                return ((double)Height / (double)Width) * 100;
            }
        }
    }
}

Etch.OrchardCore.Leaflet/Controllers/AdminController.cs
using Etch.OrchardCore.Leaflet.Models;
using Etch.OrchardCore.Leaflet.ViewModels;
using Microsoft.AspNetCore.Mvc;
using OrchardCore.ContentManagement;
using OrchardCore.ContentManagement.Metadata;
using OrchardCore.ContentManagement.Metadata.Settings;
using OrchardCore.DisplayManagement;
using OrchardCore.DisplayManagement.ModelBinding;
using System.Linq;
using System.Threading.Tasks;

namespace Etch.OrchardCore.Leaflet.Controllers
{
    public class AdminController : Controller
    {
        private readonly IContentManager _contentManager;
        private readonly IContentDefinitionManager _contentDefinitionManager;
        private readonly IShapeFactory _shapeFactory;
        private readonly IUpdateModelAccessor _updateModelAccessor;

        public AdminController(
            IContentManager contentManager,
            IContentDefinitionManager contentDefinitionManager,
            IShapeFactory shapeFactory,
            IUpdateModelAccessor updateModelAccessor)
        {
            _contentManager = contentManager;
            _contentDefinitionManager = contentDefinitionManager;
            _shapeFactory = shapeFactory;
            _updateModelAccessor = updateModelAccessor;
        }

        public async Task<IActionResult> BuildEditor(BuildEditorViewModel model)
        {
            if (string.IsNullOrWhiteSpace(model.Id))
            {
                return NotFound();
            }

            var contentItem = await _contentManager.NewAsync(model.Id);
            var cardCollectionType = nameof(MapPoisPart);

            model.EditorShape = await _shapeFactory.New.ContentCard(
                //Updater is the controller for AJAX Requests
                Updater: _updateModelAccessor.ModelUpdater,
                //Shape Specific
                CollectionShapeType: cardCollectionType,
                ContentItem: contentItem,
                BuildEditor: true,
                ParentContentType: model.ParentContentType,
                CollectionPartName: model.PartName,
                ContainedContentTypes: _contentDefinitionManager.ListTypeDefinitions().Where(t => t.GetSettings<ContentTypeSettings>().Stereotype == "POI"),
                //Card Specific Properties
                TargetId: model.TargetId,
                Inline: false,
                CanMove: false,
                CanDelete: true,
                //Input hidden
                //Prefixes
                HtmlFieldPrefix: model.Prefix,
                PrefixesId: model.PrefixesName.Replace('.', '_'),
                PrefixesName: model.PrefixesName,
                //ContentTypes
                ContentTypesId: model.ContentTypesName.Replace('.', '_'),
                ContentTypesName: model.ContentTypesName
            );

            return View("Display", model);
        }
    }
}

Etch.OrchardCore.Leaflet/Controllers/PoiController.cs
using Etch.OrchardCore.Leaflet.Models;
using Etch.OrchardCore.Leaflet.ViewModels;
using Microsoft.AspNetCore.Mvc;
using OrchardCore.ContentManagement;
using OrchardCore.ContentManagement.Display;
using OrchardCore.DisplayManagement.ModelBinding;
using System.Linq;
using System.Threading.Tasks;

namespace Etch.OrchardCore.Leaflet.Controllers
{
    public class PoiController : Controller
    {
        private readonly IContentItemDisplayManager _contentItemDisplayManager;
        private readonly IContentManager _contentManager;
        private readonly IUpdateModelAccessor _updateModelAccessor;

        public PoiController(
            IContentItemDisplayManager contentItemDisplayManager,
            IContentManager contentManager,
            IUpdateModelAccessor updateModelAccessor)
        {
            _contentItemDisplayManager = contentItemDisplayManager;
            _contentManager = contentManager;
            _updateModelAccessor = updateModelAccessor;
        }

        [ResponseCache(Duration = 300, Location = ResponseCacheLocation.Any)]
        public async Task<IActionResult> BuildDisplay(string contentItemId, string poiContentItemId)
        {
            if (string.IsNullOrWhiteSpace(contentItemId) || string.IsNullOrWhiteSpace(poiContentItemId))
            {
                return NotFound();
            }

            var contentItem = await _contentManager.GetAsync(contentItemId);

            if (contentItem == null || !contentItem.Has<MapPoisPart>())
            {
                return NotFound();
            }

            var part = contentItem.As<MapPoisPart>();
            var poiContentItem = part.ContentItems.SingleOrDefault(x => x.ContentItemId == poiContentItemId);

            if (poiContentItem == null)
            {
                return NotFound();
            }

            return View("Display", new BuildDisplayViewModel
            {
                DisplayShape = await _contentItemDisplayManager.BuildDisplayAsync(poiContentItem, _updateModelAccessor.ModelUpdater)
            });
        }
    }
}

Etch.OrchardCore.Leaflet/Views/ContentCard-MapPoisPart.Edit.cshtml
@inject OrchardCore.ContentManagement.Metadata.IContentDefinitionManager ContentDefinitionManager

@{
    ContentItem contentItem = Model.ContentItem;
    var contentType = ContentDefinitionManager.GetTypeDefinition(contentItem.ContentType).DisplayName;
}

<div class="widget widget-editor card my-1 @(Model.Inline != true ? "collapsed" : "")">
    <div class="widget-editor-header card-header text-muted py-1 pl-3 pr-1">
        @if (Model.CanMove != false)
        {
            <div class="widget-editor-handle"><span class="fas fa-arrows-alt"></span></div>
        }
        <button type="button" class="btn btn-outline-secondary btn-sm widget-editor-btn-toggle widget-editor-btn-collapse"><i class="fa fa-angle-down" aria-hidden="true"></i></button>
        <button type="button" class="btn btn-outline-secondary btn-sm widget-editor-btn-toggle widget-editor-btn-expand"><i class="fa fa-angle-up" aria-hidden="true"></i></button>
        @T["{0} — <span class=\"hint\">{1}</span>", contentItem.DisplayText, contentType]
        @if (Model.CanDelete != false)
        {
            <div class="btn-group btn-group-sm float-end" role="group">
                @* We don't render an Insert button as the container type is not known here *@
                <button type="button" class="btn btn-danger poi-delete widget-delete" data-content-item-id="@contentItem.ContentItemId" data-title="@T["Delete"]" data-message="@T["Are you sure you want to remove this item?"]"><i class="fa fa-trash" aria-hidden="true"></i></button>
            </div>
        }
    </div>
    <div class="widget-editor-body card-body px-2 py-1">
        <div class="w-100">
            @if (Model.ContentEditor != null)
            {
                @await DisplayAsync(Model.ContentEditor)
            }
        </div>
    </div>

    @* We don't render a footer *@
</div>

Etch.OrchardCore.Leaflet/Views/ContentCard-MapPoisPart.Frame.cshtml
<div class="widget-template col-md-12 px-1" id="@Model.ChildContent.PrefixValue" data-content-item-id="@Model.ChildContent.ContentItem.ContentItemId">
    @await DisplayAsync(Model.ChildContent)
</div>

Etch.OrchardCore.Leaflet/Views/Map.Edit.cshtml
@using Etch.OrchardCore.Leaflet.Models;
@using OrchardCore.ContentManagement.Metadata.Settings;

@model Etch.OrchardCore.Leaflet.ViewModels.MapEditViewModel

@inject IContentManager ContentManager
@inject OrchardCore.ContentManagement.Metadata.IContentDefinitionManager ContentDefinitionManager

@{
    var poiTemplatePlaceholderId = Html.Id("poiTemplatePlaceholderId");
    var poiContentTypes = ContentDefinitionManager.ListTypeDefinitions().Where(t => t.GetSettings<ContentTypeSettings>().Stereotype == "POI");
    var parentContentType = Model.ContentItem.ContentType;
    string partName = ((dynamic)Model).Metadata.Name;
}

<script asp-src="~/Etch.OrchardCore.Leaflet/Scripts/admin.js" asp-name="leafletmapadmin" depends-on="jquery" at="Foot"></script>
<script asp-name="jQuery-ui" at="Foot"></script>

@if (!Model.HasTiles)
{
    <p class="alert alert-warning">Unable to add POIs until map tiles has been chosen.</p>
}

@if (Model.HasTiles)
{
    <style asp-src="~/Etch.OrchardCore.Leaflet/Styles/admin.css" at="Head"></style>

    <script at="Foot">
    window.initializeMap({ domId: 'map', height: @Model.Height, isAdmin: true, isManagePOIs: true, tileRoot: '@Model.TileRoot', width: @Model.Width });
    </script>

    <div class="leaflet leaflet--admin">
        <div id="map"></div>
    </div>

    <div class="modal fade" id="modalPoiMarkers" tabindex="-1" role="dialog" aria-labelledby="poi-picker-label" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">@T["Available POIs"]</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="card-columns">
                        @foreach (var type in poiContentTypes)
                        {
                            <div class="card">
                                <div class="card-body">
                                    <h4>@type.DisplayName.Replace("POI", "")</h4>
                                </div>
                                <div class="card-footer text-muted text-xs-right">
                                    <button type="button"
                                            class="btn btn-primary btn-sm add-poi"
                                            data-icon-marker-path="@(type.Parts.SingleOrDefault(x => x.Name == nameof(PoiPart)).GetSettings<PoiPartSettings>().MarkerIcon)"
                                            data-icon-marker-height="@(type.Parts.SingleOrDefault(x => x.Name == nameof(PoiPart)).GetSettings<PoiPartSettings>().MarkerIconHeight)"
                                            data-icon-marker-width="@(type.Parts.SingleOrDefault(x => x.Name == nameof(PoiPart)).GetSettings<PoiPartSettings>().MarkerIconWidth)">
                                        @T["Add"]
                                    </button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">@T["Cancel"]</button>
                </div>
            </div>
        </div>
    </div>
}


Etch.OrchardCore.Leaflet/Views/Map.cshtml
@using Etch.OrchardCore.Leaflet.Utils 
@using Newtonsoft.Json
@using Newtonsoft.Json.Serialization

@model Etch.OrchardCore.Leaflet.ViewModels.MapViewModel

@{ 
    string analytics = JsonConvert.SerializeObject(Model.Analytics, new JsonSerializerSettings
    {
        ContractResolver = new CamelCasePropertyNamesContractResolver()
    });
}

<style asp-src="~/Etch.OrchardCore.Leaflet/Styles/map.css" at="Head" asp-append-version="true"></style>
<script asp-src="~/Etch.OrchardCore.Leaflet/Scripts/map.js" at="Foot" depends-on="jquery" asp-append-version="true"></script>

<script at="Foot">
    window.initializeMap({ 
        analytics: '@Html.Raw(analytics)', 
        contentItemId: '@Model.ContentItem.ContentItemId', 
        deepLinking: true, 
        domId: 'map', 
        draggableMarkers: false, 
        height: @Model.Height, 
        initialZoom: @Model.InitialZoom, 
        maxZoom: @Model.MaxZoom, 
        minZoom: @Model.MinZoom, 
        mouseWheelZoom: @Model.MouseWheelZoom.ToString().ToLower(), 
        poiDisplayUrl: '@Url.Action("BuildDisplay", "Poi", new { area = "Etch.OrchardCore.Leaflet" })', 
        pois: '@Html.Raw(PoiUtils.Serialize(Model.Markers))', 
        tileRoot: '@Model.TileRoot', 
        width: @Model.Width, 
        zoomControlPosition: '@Model.ZoomControlPosition' 
    });
</script>

<div class="leaflet" style="padding-bottom: @Model.Ratio.ToString("#.000")%;">
    <div id="map"></div>
</div>

Etch.OrchardCore.Leaflet/Views/MapPoisPart.Edit.cshtml
@using Etch.OrchardCore.Leaflet.Models;
@using Etch.OrchardCore.Leaflet.Utils;
@using Newtonsoft.Json;
@using Newtonsoft.Json.Serialization;
@using OrchardCore.ContentManagement.Display;
@using OrchardCore.ContentManagement.Metadata;
@using OrchardCore.ContentManagement.Metadata.Settings;
@using OrchardCore.Mvc.Utilities;

@model Etch.OrchardCore.Leaflet.ViewModels.MapPoisEditViewModel

@inject IContentManager ContentManager
@inject IContentDefinitionManager ContentDefinitionManager
@inject IContentItemDisplayManager ContentItemDisplayManager

@{
    var htmlFieldPrefix = ViewContext.ViewData.TemplateInfo.HtmlFieldPrefix;
    var poiTemplatePlaceholderId = Html.Id("poiTemplatePlaceholderId");
    var poiContentTypes = ContentDefinitionManager.ListTypeDefinitions().Where(t => t.Parts.Any(x => x.Name.Equals(nameof(PoiPart))));
    var parentContentType = Model.ContentItem.ContentType;
    var map = Model.ContentItem.As<Map>();


    string partName = ((dynamic)Model).Metadata.Name;
}

<script asp-src="~/Etch.OrchardCore.Leaflet/Scripts/admin.js" depends-on="admin, jquery" at="Foot" asp-append-version="true"></script>
<script asp-name="jQuery-ui" at="Foot"></script>

@if (!Model.HasTiles)
{
    <p class="alert alert-warning">@T["Unable to add POIs until map tiles has been chosen."]</p>
}

@if (Model.HasTiles)
{
    <style asp-src="~/Etch.OrchardCore.Leaflet/Styles/admin.css" at="Head" asp-append-version="true"></style>

    <script at="Foot">
        window.initializeMap({ 
            domId: 'map', 
            draggableMarkers: true, 
            height: @Model.Height, 
            initialZoom: @map.InitialZoom, 
            maxZoom: @map.MaxZoom,
            minZoom: @map.MinZoom,
            mouseWheelZoom: false,
            pois: '@Html.Raw(PoiUtils.Serialize(Model.Markers))', 
            tileRoot: '@Model.TileRoot', 
            width: @Model.Width, 
            zoomControlPosition: 'topleft' });
    </script>

    <div class="leaflet leaflet--admin">
        <div id="map"></div>
    </div>

    <div class="mb-3">
        <h3>@T["POIs"]</h3>

        <p class="hint">@T["Click on map to add new POI."]</p>

        <div id="@poiTemplatePlaceholderId" class="widget-template-placeholder widget-template-placeholder-bagpart bagpart-@partName.HtmlClassify() row mx-0" data-buildeditorurl="@Url.Action("BuildEditor", "Admin", new { area = "Etch.OrchardCore.Leaflet" })">
            @foreach (var poi in Model.MapPoisPart.ContentItems)
            {
                var index = 0;

                //Create a Card Shape
                dynamic contentCard = await New.ContentCard(
                    // FOR Updater
                    CollectionShape: Model,
                    //Shape Specific
                    CollectionShapeType: nameof(MapPoisPart),
                    ContentItem: poi,
                    BuildEditor: true,
                    ParentContentType: parentContentType,
                    CollectionPartName: partName,
                    //Card Specific Properties
                    TargetId: poiContentTypes,
                    Inline: false,
                    CanMove: false,
                    CanDelete: true,
                    //Input hidden
                    //Prefixes
                    PrefixValue: htmlFieldPrefix + '-' + (index++).ToString(),
                    HtmlFieldPrefix: htmlFieldPrefix,
                    PrefixesId: Html.IdFor(x => x.Prefixes),
                    PrefixesName: Html.NameFor(x => x.Prefixes),
                    //Content Types
                    ContentTypesId: Html.IdFor(x => x.ContentTypes),
                    ContentTypesName: Html.NameFor(x => x.ContentTypes),
                    ContentItemsId: Html.IdFor(x => x.ContentItems),
                    ContentItemsName: Html.NameFor(x => x.ContentItems)
                );

                @await DisplayAsync(contentCard)
            }
        </div>
    </div>

    @* Rendered only once in case multiple MapPoisPart are on the page *@
    @if (Context.Items["MapPoisPart.Edit"] == null)
    {
        Context.Items["MapPoisPart.Edit"] = new object();
        <script asp-src="~/OrchardCore.Flows/Scripts/flows.edit.min.js"
                debug-src="~/OrchardCore.Flows/Scripts/flows.edit.js" at="Foot" depends-on="admin"></script>
        <style asp-src="~/OrchardCore.Widgets/Styles/widgetslist.edit.min.css"
               debug-src="~/OrchardCore.Widgets/Styles/widgetslist.edit.css"></style>
        <style asp-src="~/OrchardCore.Flows/Styles/flows.edit.min.css"
               debug-src="~/OrchardCore.Flows/Styles/flows.edit.css"></style>
    }

    @* Rendered only once per type to initialize the scripts its editor will need *@
    @foreach (var type in poiContentTypes)
    {
        @if (Context.Items["MapPoisPart.Edit:" + type.Name] == null)
        {
            Context.Items["MapPoisPart.Edit:" + type.Name] = new object();

            // Render a mock widget so that its resources are included in the page
            var contentItem = await ContentManager.NewAsync(type.Name);
            await DisplayAsync(await ContentItemDisplayManager.BuildEditorAsync(contentItem, Model.Updater, true, "", Guid.NewGuid().ToString("n")));
        }
    }

    <div class="modal fade" id="modalPoiMarkers" tabindex="-1" role="dialog" aria-labelledby="poi-picker-label" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">@T["Available POIs"]</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row row-cols-1 row-cols-md-3 g-2">
                        @foreach (var type in poiContentTypes)
                        {
                            <div class="col activity widget">
                                <div class="card h-100">
                                    <div class="card-body">
                                        <h4 class="card-title">@type.DisplayName.Replace("POI", "")</h4>
                                        <p>@type.Settings["Description"]</p>
                                    </div>
                                    <div class="card-footer text-muted text-sm-end">
                                        <button type="button"
                                                class="btn btn-primary btn-sm add-poi"
                                                data-target-id="@poiTemplatePlaceholderId"
                                                data-parent-content-type="@parentContentType"
                                                data-part-name="@partName"
                                                data-prefixes-name="@Html.NameFor(x => x.Prefixes)"
                                                data-contenttypes-name="@Html.NameFor(x => x.ContentTypes)"
                                                data-contentitems-name="@Html.NameFor(x => x.ContentItems)"
                                                data-widget-type="@type.Name"
                                                data-bs-dismiss="modal"
                                                href="javascript:;"
                                                data-icon-marker-path="@(type.Parts.SingleOrDefault(x => x.Name == nameof(PoiPart)).GetSettings<PoiPartSettings>().AdminMarkerIconPath)"
                                                data-icon-marker-height="@(type.Parts.SingleOrDefault(x => x.Name == nameof(PoiPart)).GetSettings<PoiPartSettings>().MarkerIconHeight)"
                                                data-icon-marker-width="@(type.Parts.SingleOrDefault(x => x.Name == nameof(PoiPart)).GetSettings<PoiPartSettings>().MarkerIconWidth)"
                                                data-icon-marker-zoom-ratio="@(type.Parts.SingleOrDefault(x => x.Name == nameof(PoiPart)).GetSettings<PoiPartSettings>().MarkerIconZoomRatio)">
                                            @T["Add"]
                                        </button>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">@T["Cancel"]</button>
                </div>
            </div>
        </div>
    </div>
}


Etch.OrchardCore.Leaflet/Views/MapPoisPart.Fields.Edit.cshtml
<input type="hidden" id="@Model.CardShape.PrefixesId" name="@Model.CardShape.PrefixesName" value="@Model.CardShape.PrefixValue" />
<input type="hidden" id="@Model.CardShape.ContentTypesId" name="@Model.CardShape.ContentTypesName" value="@Model.CardShape.ContentItem.ContentType" />

Etch.OrchardCore.Leaflet/Views/MapTiles.Edit.cshtml
@model Etch.OrchardCore.Leaflet.ViewModels.MapTilesViewModel

@{
    var isNew = !Model.ContentItem.CreatedUtc.HasValue;
}

<script asp-src="~/Etch.OrchardCore.Leaflet/Scripts/admin.js" depends-on="jquery" at="Foot" asp-append-version="true"></script>

@if (Model.IsAutogenerated && isNew)
{
    <div class="alert alert-warning" role="alert">@T["Tiles will be generated after creation."]</div>

    <div class="form-group">
        <div class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input" asp-for="PublishAfterProcessed" checked="@Model.PublishAfterProcessed" />
            <label class="custom-control-label" asp-for="PublishAfterProcessed">@T["Publish after processed"]</label>
            <span class="hint">— @T["Check to publish content item after tiles have been generated."]</span>
        </div>
    </div>
}

@if (Model.IsAutogenerated && !isNew && !Model.HasBeenProcessed)
{
    <div class="alert alert-warning" role="alert">@T["Tiles are waiting to be generated."]</div>
}

@if (Model.IsAutogenerated && !isNew && Model.IsProcessing)
{
    <div class="alert alert-warning" role="alert">@T["Tiles are being generated."]</div>
}

@if (!Model.IsProcessing && Model.HasBeenProcessed)
{
    <style asp-src="~/Etch.OrchardCore.Leaflet/Styles/admin.css" at="Head" asp-append-version="true"></style>

    <script at="Foot">
    window.initializeMap({ 
        domId: 'map', 
        height: @Model.Height,
        mouseWheelZoom: true,
        tileRoot: '@Model.TileRoot', 
        width: @Model.Width, 
        zoomControlPosition: 'topleft' 
    });
    </script>

    <h4>@T["Preview"]</h4>

    <div class="leaflet leaflet--admin">
        <div id="map"></div>
    </div>
}

@Html.HiddenFor(x => x.Height)
@Html.HiddenFor(x => x.Width)

Etch.OrchardCore.Leaflet/Views/MapTilesManualPart.Edit.cshtml
@model Etch.OrchardCore.Leaflet.ViewModels.MapTilesManualPartEditViewModel

<div class="form-group">
    <label asp-for="TilesRoot">@T["Tiles Root"]</label>
    <input asp-for="TilesRoot" class="form-control" />
    <span class="hint">@T["Path to directory within the media library that contains the tiles (e.g. \"/Map/Tiles\")"]</span>
    <span asp-validation-for="TilesRoot"></span>
</div>

Etch.OrchardCore.Leaflet/Views/POI.Edit.cshtml
@{
    Model.Metadata.Type = "Content_Edit";
    @await DisplayAsync(Model)
}

Etch.OrchardCore.Leaflet/Views/POI.cshtml
@using OrchardCore.Mvc.Utilities;

@{
    Model.Classes.Add("content-item");

    var contentTypeClassName = ((string)Model.ContentItem.ContentType).HtmlClassify();
    Model.Classes.Add(contentTypeClassName);
}

<article class="@String.Join(" ", Model.Classes.ToArray())">
    @if (Model.Header != null || Model.Meta != null)
    {
        <header>
            @await DisplayAsync(Model.Header)
            @if (Model.Meta != null)
            {
                <div class="metadata">
                    @await DisplayAsync(Model.Meta)
                </div>
            }
        </header>
    }
    @await DisplayAsync(Model.Content)
    @if (Model.Footer != null)
    {
        <footer>
            @await DisplayAsync(Model.Footer)
        </footer>
    }
</article>

Etch.OrchardCore.Leaflet/Views/PoiPart.Edit.cshtml
@model Etch.OrchardCore.Leaflet.ViewModels.PoiPartEditViewModel

<div class="form-group" asp-validation-class-for="Latitude">
    <label asp-for="Latitude">@T["Latitude"]</label>
    <input asp-for="Latitude" class="form-control" readonly="readonly" />
    <span asp-validation-for="Latitude"></span>
</div>

<div class="form-group" asp-validation-class-for="Longitude">
    <label asp-for="Longitude">@T["Longitude"]</label>
    <input asp-for="Longitude" class="form-control" readonly="readonly" />
    <span asp-validation-for="Longitude"></span>
</div>

<p class="hint">@T["Change position of POI by dragging marker on map."]</p>

Etch.OrchardCore.Leaflet/Views/PoiPartSettings.Edit.cshtml
@model Etch.OrchardCore.Leaflet.ViewModels.PoiPartSettingsViewModel

<div class="form-group">
    <label asp-for="MarkerIcon">@T["Marker Icon"]</label>
    <input asp-for="MarkerIcon" class="form-control" />
    <span class="hint">@T["Path to icon to be used as POI marker."]</span>
</div>

<div class="form-group">
    <label asp-for="MarkerHoverIcon">@T["Marker Hover Icon"]</label>
    <input asp-for="MarkerHoverIcon" class="form-control" />
    <span class="hint">@T["Path to icon that will display when user hovers over POI."]</span>
</div>


<div class="form-group">
    <label asp-for="MarkerAdminIcon">@T["Admin Marker Icon"]</label>
    <input asp-for="MarkerAdminIcon" class="form-control" />
    <span class="hint">@T["Path to icon to be used as POI marker when defining POIs in admin area. Leave blank to use same as marker icon."]</span>
</div>

<div class="form-group">
    <label asp-for="MarkerIconHeight">@T["Marker Icon Height"]</label>
    <input asp-for="MarkerIconHeight" class="form-control" />
    <span class="hint">@T["Height to of POI marker icon."]</span>
</div>

<div class="form-group">
    <label asp-for="MarkerIconWidth">@T["Marker Icon Width"]</label>
    <input asp-for="MarkerIconWidth" class="form-control" />
    <span class="hint">@T["Width to of POI marker icon."]</span>
</div>

<div class="form-group">
    <label asp-for="MarkerIconZoomRatio">@T["Marker Icon Zoom Ratio"]</label>
    <input asp-for="MarkerIconZoomRatio" class="form-control" />
    <span class="hint">@T["Ratio used to determine marker dimensions when zooming in to map."]</span>
</div>
